### ISSUE TITLE
Could not support jupyterlab 3.0

### ISSUE THREAD

**Issue by lydmom** [krassowski/jupyterlab-spreadsheet-editor#16]
Hi, after upgrade jupyter-lab, the extension not longer work, could you please fix it? I found your extension is very useful. Thank you.
`Conflicting Dependencies:
JupyterLab                 Extension      Package
>=3.0.3 <3.1.0             >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0             >=2.2.0 <3.0.0 @jupyterlab/apputils
>=5.0.1 <5.1.0             >=4.2.0 <5.0.0 @jupyterlab/coreutils
>=3.0.3 <3.1.0             >=2.2.0 <3.0.0 @jupyterlab/documentsearch
>=3.0.2 <3.1.0             >=2.2.2 <3.0.0 @jupyterlab/launcher
>=3.0.2 <3.1.0             >=2.1.1 <3.0.0 @jupyterlab/mainmenu
>=6.0.2 <6.1.0             >=5.2.1 <6.0.0 @jupyterlab/services
See the log file for details:  /tmp/jupyterlab-debug-tew_5_t9.log`

**Comment by pressla** [comment]
same for me. 
![image](https://user-images.githubusercontent.com/6031133/107130356-c86aed80-68cc-11eb-8f9d-b6d394bc0ddf.png)
